/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:d878c8d8-fc4f-4a32-9f26-8257a762f1c8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_LXsJUbJ45",
    "aws_user_pools_web_client_id": "22vt6j2sv3nbf142nqgjur2mji",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ppx5gt6o5rei7fonbmwniqhfoe.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-kwem5zg3lng2payh67kw4r4jpm",
    "aws_user_files_s3_bucket": "meinblog019e64b90d6c4b6bbebafaff0a641e3d231157-staging",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
